VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsWrapperControl"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit
'
''clsControlWrapper - 2025-05-30 @ 13:24
'
'Private wrappers As Collection
'Public WithEvents ctrl As MSForms.Control
'
'Private Sub ctrl_Change()
'
'    Call EnregistrerActivite(ctrl.Name & "-" & TypeName(ctrl) & " [" & Fn_NomFeuilleActive() & "]")
'
'End Sub
'
'Private Sub ctrl_Click()
'
'    Call EnregistrerActivite(ctrl.Name & "-" & TypeName(ctrl) & " [" & Fn_NomFeuilleActive() & "]")
'
'End Sub
'
'Private Sub ctrl_Enter()
'
'    Call EnregistrerActivite(ctrl.Name & "-" & TypeName(ctrl) & " [" & Fn_NomFeuilleActive() & "]")
'
'End Sub
'
'Private Sub ctrl_Exit(ByVal Cancel As MSForms.ReturnBoolean)
'
'    Call EnregistrerActivite(ctrl.Name & "-" & TypeName(ctrl) & " [" & Fn_NomFeuilleActive() & "]")
'
'End Sub
'
'Private Sub ctrl_KeyDown(ByVal KeyCode As Integer, ByVal Shift As Integer)
'
'    Call EnregistrerActivite(ctrl.Name & "-" & TypeName(ctrl) & " [" & Fn_NomFeuilleActive() & "]")
'
'End Sub
'
'Private Sub ctrl_KeyUp(ByVal KeyCode As Integer, ByVal Shift As Integer)
'
'    Call EnregistrerActivite(ctrl.Name & "-" & TypeName(ctrl) & " [" & Fn_NomFeuilleActive() & "]")
'
'End Sub
'
'Private Sub ctrl_MouseDown(ByVal Button As Integer, ByVal Shift As Integer, ByVal X As Single, ByVal Y As Single)
'
'    Call EnregistrerActivite(ctrl.Name & "-" & TypeName(ctrl) & " [" & Fn_NomFeuilleActive() & "]")
'
'End Sub
'
